version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing required packages..."
      - apt-get update
      - apt-get install -y unzip zip
  pre_build:
    commands:
      - echo "Setting up permissions and environment..."
      - chmod +x gradlew
  build:
    commands:
      - echo "Building the Android APK..."
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo "Build complete. Preparing artifacts..."

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
